site_name: roman's notes ■
site_url: https://romanpilyushin.github.io
theme:
  logo: logo.png
  favicon: logo.png
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - header.autohide
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.footer
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: black
      accent: light green
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: black
      accent: light green
markdown_extensions:
  - attr_list
plugins:
  - search
  - blog:
      post_excerpt: optional
      archive_date_format: MMMM yyyy
      archive_toc: true
      blog_toc: true
      post_excerpt_separator: <!-- more -->
      archive: true
  - tags:
      tags_file: blog/tags.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/RomanPilyushin
copyright: Copyright &copy; 2020 - 2024 Roman Pilyushin